<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/styles/master.css" type="text/css" media="screen" charset="utf-8" />
	<script src="<?=$this->baseUrl?>/scripts/jquery-1.2.6.min.js" type="text/javascript"></script>
	<title>Webhouse</title>
	<style type="css"></style>
</head>
<body>
<div id="header"></div>
<div id="wrapper" class="container_16">
	<div id="menubar">
		<ul id="menu">
			<li><a href="<?= $this->baseUrl ?>/">Početna</a></li>
			<li><a href="<?= $this->baseUrl ?>/ponuda">Ponuda</a></li>
			<li><a href="<?= $this->baseUrl ?>/pitanja">Pitanja</a></li>
			<li><a href="<?= $this->baseUrl ?>/onama">O nama</a></li>
		</ul>
		<input id="searchbox" type="text" value="pretraga..." />
	</div>
	<div id="pathbar" class="grid_16">&nbsp;</div>
	<div id="sidebar" class="grid_4">&nbsp;</div>
	<div id="content" class="grid_12">&nbsp;
		<?= $this->layout()->content; ?>
	</div>
	<br class="clear" />
</div>
</body>
</html>