<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/styles/master.css" type="text/css" media="screen" charset="utf-8" />
	<script src="<?=$this->baseUrl?>/scripts/jquery-1.2.6.min.js" type="text/javascript"></script>
	<title>Webhouse</title>
	<style type="css"></style>
</head>
<body>
<div id="header"></div>
<div id="wrapper" class="container_16">
	<div id="menubar">
		<ul id="menu">
			<li><a href="<?= $this->baseUrl ?>/product/category">Ponuda</a></li>
			<li><a href="<?= $this->baseUrl ?>/cart">Košarica</a></li>
		</ul>
        <form id="search" method="post" action="<?= $this->baseUrl ?>/search/query">
            <input id="searchbox" type="text" value="pretraga..." onclick="javascript: if(this.value == 'pretraga...') this.value = ''" onblur="javascript: if(this.value == '') this.value = 'pretraga...'" name="query" />
        </form>
	</div>
	<div id="pathbar" class="grid_16">
		<?php
			$cart = new Cart();
			$count = $cart->calcAmount();
            $total = $cart->getTotal();
            $customer = new Customer();
            $curcust =  $customer->getCustomer();
            if($customer->isLoggedIn()) $login = "Hello, " . $curcust->customerFirstname . " (<a href=$this->baseUrl/auth/logout>Logout</a>) |";
            else $login = "<a href='$this->baseUrl/auth/'>Log in</a> |";

            $session = new SessionLog();
            $time = $session->getTime(true);
		?>
        <div class="info"><p>Vrijeme: <?= $time ?></p></div>
		<div class="cart"><p><?= $login ?> <a href="<?= $this->baseUrl ?>/cart"><?= $count ?> artikla (<?= $total ?>kn) <img src="<?= $this->baseUrl ?>/images/icons/cart_go.png" /></a></p></div>
	</div>
	<div id="sidebar" class="grid_4">
		<?= $this->layout()->sidebar; ?>
	</div>
	<div id="content" class="grid_12">&nbsp;
		<?= $this->layout()->content; ?>
	</div>
	<br class="clear" />
</div>
</body>
</html>