<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/styles/master.css" type="text/css" media="screen" charset="utf-8" />
	<script src="<?=$this->baseUrl?>/scripts/jquery-1.2.6.min.js" type="text/javascript"></script>
	<title>Webhouse</title>
</head>
<body>


<?= $this->layout()->content; ?>


</body>
</html>